diff --git a/drivers/media/platform/exynos/fimc-is2/sensor/module_framework/Makefile b/drivers/media/platform/exynos/fimc-is2/sensor/module_framework/Makefile
new file mode 100644
index 000000000000..465da5f29d6d
--- /dev/null
+++ b/drivers/media/platform/exynos/fimc-is2/sensor/module_framework/Makefile
@@ -0,0 +1,8 @@
+obj-$(CONFIG_USE_DIRECT_IS_CONTROL)	+= fimc-is-interface-sensor.o \
+				       fimc-is-interface-actuator.o \
+				       fimc-is-control-sensor.o \
+				       fimc-is-control-actuator.o \
+				       fimc-is-device-sensor-peri.o
+
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
