diff --git a/drivers/five/Makefile b/drivers/five/Makefile
new file mode 100644
index 000000000000..dd6b6d101a2a
--- /dev/null
+++ b/drivers/five/Makefile
@@ -0,0 +1,2 @@
+# Integrity TEE Driver
+obj-$(CONFIG_FIVE_TEE_DRIVER) += five_tee_driver/
