diff --git a/drivers/input/keyboard/Makefile b/drivers/input/keyboard/Makefile
index 0a3345634d79..c92813ad0362 100644
--- a/drivers/input/keyboard/Makefile
+++ b/drivers/input/keyboard/Makefile
@@ -59,3 +59,12 @@ obj-$(CONFIG_KEYBOARD_TEGRA)		+= tegra-kbc.o
 obj-$(CONFIG_KEYBOARD_TWL4030)		+= twl4030_keypad.o
 obj-$(CONFIG_KEYBOARD_XTKBD)		+= xtkbd.o
 obj-$(CONFIG_KEYBOARD_W90P910)		+= w90p910_keypad.o
+obj-$(CONFIG_KEYBOARD_TC300K)		+= tc300k.o
+obj-$(CONFIG_KEYBOARD_ABOV_TOUCH_FT1804)	+= abov_touchkey_ft1804.o
+obj-$(CONFIG_KEYBOARD_ABOV_TOUCH_T316)	+= abov_touchkey_ft1804.o
+obj-$(CONFIG_KEYBOARD_ABOV_TOUCH_3X6)	+= abov_touchkey_3x6.o
+obj-$(CONFIG_KEYBOARD_ABOV_TOUCH)	+= abov_touchkey.o
+obj-$(CONFIG_KEYBOARD_MELFAS_MHS204) += melfas_mip4/
+obj-$(CONFIG_KEYBOARD_MELFAS_MHS204G) += melfas_mip4/
+obj-$(CONFIG_KEYBOARD_MELFAS_MHS2041) += melfas_mip4/
+obj-$(CONFIG_KEYBOARD_MELFAS_MHS2041B) += melfas_mip4/
