diff --git a/drivers/input/touchscreen/imagis_30xxc/Makefile b/drivers/input/touchscreen/imagis_30xxc/Makefile
new file mode 100644
index 000000000000..e86dcd2be753
--- /dev/null
+++ b/drivers/input/touchscreen/imagis_30xxc/Makefile
@@ -0,0 +1,12 @@
+#
+# Makefile for the Imagis touch driver
+#
+
+# Each configuration option enables a list of files.
+
+obj-$(CONFIG_TOUCHSCREEN_IST30XXC)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_sec.o ist30xxc_cmcs.o
+obj-$(CONFIG_TOUCHSCREEN_IST3026C)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_sec.o ist30xxc_cmcs.o
+obj-$(CONFIG_TOUCHSCREEN_IST3032C)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_sec.o ist30xxc_cmcs.o
+obj-$(CONFIG_TOUCHSCREEN_IST3038C)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_sec.o ist30xxc_cmcs.o
+obj-$(CONFIG_TOUCHSCREEN_IST3044C)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_sec.o ist30xxc_cmcs.o
+obj-$(CONFIG_TOUCHSCREEN_IST3048C)  += ist30xxc.o ist30xxc_misc.o ist30xxc_sys.o ist30xxc_update.o ist30xxc_tracking.o ist30xxc_sec.o ist30xxc_cmcs.o
