diff --git a/init/Makefile b/init/Makefile
index 243f61de2cba..a6d79459c773 100644
--- a/init/Makefile
+++ b/init/Makefile
@@ -7,6 +7,11 @@ obj-y                          += noinitramfs.o
 obj-$(CONFIG_BLK_DEV_INITRD)   += initramfs.o
 obj-$(CONFIG_GENERIC_CALIBRATE_DELAY) += calibrate.o
 
+ifeq ($(CONFIG_TIMA_RKP), y)
+obj-y += _vmm.o vmm.o
+obj-y += ld.o
+endif
+
 ifneq ($(CONFIG_ARCH_INIT_TASK),y)
 obj-y                          += init_task.o
 endif
