diff --git a/sound/soc/samsung/Makefile b/sound/soc/samsung/Makefile
index 91505ddaaf95..9af9bce3b9fe 100644
--- a/sound/soc/samsung/Makefile
+++ b/sound/soc/samsung/Makefile
@@ -1,4 +1,5 @@
 # S3c24XX Platform Support
+snd-soc-s3c24xx-objs := dma.o
 snd-soc-s3c-dma-objs := dmaengine.o
 snd-soc-idma-objs := idma.o
 snd-soc-s3c24xx-i2s-objs := s3c24xx-i2s.o
@@ -8,8 +9,13 @@ snd-soc-s3c-i2s-v2-objs := s3c-i2s-v2.o
 snd-soc-samsung-spdif-objs := spdif.o
 snd-soc-pcm-objs := pcm.o
 snd-soc-i2s-objs := i2s.o
+snd-soc-lpass-objs := lpass.o
+snd-soc-compr-objs := compr.o visualizercap-dummydai.o
+snd-soc-eax-dai-objs := eax-dai.o
+snd-soc-eax-dma-objs := eax-dma.o
+snd-soc-esa-sa-effect-objs := esa_sa_effect.o
 
-obj-$(CONFIG_SND_SOC_SAMSUNG) += snd-soc-s3c-dma.o
+obj-$(CONFIG_SND_SOC_SAMSUNG) += snd-soc-s3c24xx.o
 obj-$(CONFIG_SND_S3C24XX_I2S) += snd-soc-s3c24xx-i2s.o
 obj-$(CONFIG_SND_SAMSUNG_AC97) += snd-soc-ac97.o
 obj-$(CONFIG_SND_S3C2412_SOC_I2S) += snd-soc-s3c2412-i2s.o
@@ -18,6 +24,20 @@ obj-$(CONFIG_SND_SAMSUNG_SPDIF) += snd-soc-samsung-spdif.o
 obj-$(CONFIG_SND_SAMSUNG_PCM) += snd-soc-pcm.o
 obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-i2s.o
 obj-$(CONFIG_SND_SAMSUNG_I2S) += snd-soc-idma.o
+obj-$(CONFIG_SND_SAMSUNG_COMPR) += snd-soc-compr.o
+
+ifeq ($(CONFIG_SND_SAMSUNG_AUDSS),y)
+obj-$(CONFIG_SOC_EXYNOS5422) += lpass.o lpass-exynos5422.o
+obj-$(CONFIG_SOC_EXYNOS5430) += lpass.o lpass-exynos5430.o
+obj-$(CONFIG_SOC_EXYNOS5433) += lpass.o lpass-exynos5433.o
+obj-$(CONFIG_SOC_EXYNOS7420) += lpass.o lpass-exynos7420.o
+obj-$(CONFIG_SOC_EXYNOS7580) += lpass.o lpass-exynos7580.o
+obj-$(CONFIG_SOC_EXYNOS7890) += lpass.o lpass-exynos7890.o
+obj-$(CONFIG_SOC_EXYNOS8890) += lpass.o lpass-exynos8890.o
+obj-$(CONFIG_SOC_EXYNOS7870) += lpass-exynos7870.o
+endif
+obj-$(CONFIG_SND_SOC_SAMSUNG) += snd-soc-eax-dai.o snd-soc-eax-dma.o
+obj-$(CONFIG_SND_ESA_SA_EFFECT) += snd-soc-esa-sa-effect.o
 
 # S3C24XX Machine Support
 snd-soc-jive-wm8750-objs := jive_wm8750.o
@@ -45,6 +65,15 @@ snd-soc-lowland-objs := lowland.o
 snd-soc-littlemill-objs := littlemill.o
 snd-soc-bells-objs := bells.o
 snd-soc-odroidx2-max98090-objs := odroidx2_max98090.o
+snd-soc-universal8890-dummy-objs := universal8890_dummy.o
+snd-soc-smdk7870-cod3026x-objs := smdk7870-cod3026.o
+ifeq ($(CONFIG_SND_SOC_EXYNOS_AUDMIXER_VER),2)
+snd-soc-universal7870-cod3026x-v2-objs := universal7870-cod3026-v2.o
+else
+snd-soc-universal7870-cod3026x-objs := universal7870-cod3026.o
+endif
+snd-soc-universal7870-rt5659-objs := universal7870-rt5659.o
+snd-soc-espresso8890-wm5110-objs := cp_dummy.o espresso8890_wm5110.o
 
 obj-$(CONFIG_SND_SOC_SAMSUNG_JIVE_WM8750) += snd-soc-jive-wm8750.o
 obj-$(CONFIG_SND_SOC_SAMSUNG_NEO1973_WM8753) += snd-soc-neo1973-wm8753.o
@@ -71,3 +100,14 @@ obj-$(CONFIG_SND_SOC_LOWLAND) += snd-soc-lowland.o
 obj-$(CONFIG_SND_SOC_LITTLEMILL) += snd-soc-littlemill.o
 obj-$(CONFIG_SND_SOC_BELLS) += snd-soc-bells.o
 obj-$(CONFIG_SND_SOC_ODROIDX2) += snd-soc-odroidx2-max98090.o
+obj-$(CONFIG_SND_SOC_SAMSUNG_ESPRESSO8890_WM5110) += snd-soc-espresso8890-wm5110.o
+obj-$(CONFIG_SND_SOC_SAMSUNG_UNIVERSAL8890_DUMMY) += snd-soc-universal8890-dummy.o
+obj-$(CONFIG_SND_SOC_SAMSUNG_SMDK7870_COD3026X) += snd-soc-smdk7870-cod3026x.o
+ifeq ($(CONFIG_SND_SOC_EXYNOS_AUDMIXER_VER),2)
+obj-$(CONFIG_SND_SOC_SAMSUNG_UNIVERSAL7870_COD3026X) += snd-soc-universal7870-cod3026x-v2.o
+else
+obj-$(CONFIG_SND_SOC_SAMSUNG_UNIVERSAL7870_COD3026X) += snd-soc-universal7870-cod3026x.o
+endif
+obj-$(CONFIG_SND_SOC_SAMSUNG_UNIVERSAL7870_RT5659) += snd-soc-universal7870-rt5659.o
+
+obj-$(CONFIG_SND_SAMSUNG_SEIREN) += seiren/
