diff --git a/drivers/input/touchscreen/Makefile b/drivers/input/touchscreen/Makefile
index 090e61cc9171..5f2846ef36a3 100644
--- a/drivers/input/touchscreen/Makefile
+++ b/drivers/input/touchscreen/Makefile
@@ -79,3 +79,25 @@ obj-$(CONFIG_TOUCHSCREEN_WM97XX_ZYLONITE)	+= zylonite-wm97xx.o
 obj-$(CONFIG_TOUCHSCREEN_W90X900)	+= w90p910_ts.o
 obj-$(CONFIG_TOUCHSCREEN_TPS6507X)	+= tps6507x-ts.o
 obj-$(CONFIG_TOUCHSCREEN_ZFORCE)	+= zforce_ts.o
+obj-$(CONFIG_TOUCHSCREEN_MXT540E)       += mxt540e.o
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_DSX) += synaptics_dsx/
+obj-$(CONFIG_TOUCHSCREEN_FTS)          += stm/
+obj-$(CONFIG_TOUCHSCREEN_FTS7)		+= stm/fts7/
+obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS449)	+= melfas_mms400/
+obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438)	+= melfas_mms400/
+obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438S)	+= melfas_mms400/
+obj-$(CONFIG_TOUCHSCREEN_ATMEL_MXT1664)    += mxt_t/
+obj-$(CONFIG_TOUCHSCREEN_IST3032C) += imagis_30xxc/
+obj-$(CONFIG_TOUCHSCREEN_IST3038H) += imagis_30xxh/
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT532) += zinitix/
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_BT541C) += zinitix/
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX) += zinitix/
+obj-$(CONFIG_TOUCHSCREEN_ZINITIX_ZT75XX_TCLM) += zinitix/
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_DSX_v26) += synaptics_dsx_2.6/
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_DSX2) += synaptics_dsx2/
+obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) +=cyttsp5/
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_TD4X00) += synaptics_td4x00/
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_TD4X01_A2CORELTE) += synaptics_td4x00/
+obj-$(CONFIG_TOUCHSCREEN_SEC_INCELL_TS) += sec_incell_ts/
+obj-$(CONFIG_TOUCHSCREEN_SEC_TS) += sec_ts/
+obj-$(CONFIG_TOUCHSCREEN_FTS1BA90A)	+= stm_fts1ba90a/
