diff --git a/drivers/media/platform/exynos/fimc-is2/ischain/fimc-is-v5_10_0/Makefile b/drivers/media/platform/exynos/fimc-is2/ischain/fimc-is-v5_10_0/Makefile
new file mode 100644
index 000000000000..c013fe1622d7
--- /dev/null
+++ b/drivers/media/platform/exynos/fimc-is2/ischain/fimc-is-v5_10_0/Makefile
@@ -0,0 +1,15 @@
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-hw-pwr.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-hw-chain.o
+
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-3aa.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-3ac.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-3ap.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-isp.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-ixc.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-ixp.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-mcs.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-mcsp.o
+obj-$(CONFIG_FIMC_IS_V5_10_0) += fimc-is-subdev-vra.o
+
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
