diff --git a/drivers/input/touchscreen/sec_ts/Makefile b/drivers/input/touchscreen/sec_ts/Makefile
new file mode 100644
index 000000000000..91146e83a7f8
--- /dev/null
+++ b/drivers/input/touchscreen/sec_ts/Makefile
@@ -0,0 +1,5 @@
+ifeq ($(CONFIG_SAMSUNG_PRODUCT_SHIP), y)
+  obj-$(CONFIG_TOUCHSCREEN_SEC_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_ioctl.o
+else
+  obj-$(CONFIG_TOUCHSCREEN_SEC_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_ioctl.o sec_ts_only_vendor.o
+endif
