diff --git a/drivers/net/wireless/Makefile b/drivers/net/wireless/Makefile
index 0c8891686718..d0c44688c407 100644
--- a/drivers/net/wireless/Makefile
+++ b/drivers/net/wireless/Makefile
@@ -11,7 +11,7 @@ obj-$(CONFIG_AIRO)		+= airo.o
 obj-$(CONFIG_AIRO_CS)		+= airo_cs.o airo.o
 
 obj-$(CONFIG_ATMEL)             += atmel.o
-obj-$(CONFIG_PCI_ATMEL)         += atmel_pci.o 
+obj-$(CONFIG_PCI_ATMEL)         += atmel_pci.o
 obj-$(CONFIG_PCMCIA_ATMEL)      += atmel_cs.o
 
 obj-$(CONFIG_AT76C50X_USB)      += at76c50x-usb.o
@@ -55,8 +55,33 @@ obj-$(CONFIG_WL_TI)	+= ti/
 
 obj-$(CONFIG_MWIFIEX)	+= mwifiex/
 
+ifneq ($(CONFIG_BCM4343),)
+obj-$(CONFIG_BCM4343)   += bcmdhd_100_10/
+obj-$(CONFIG_BCM4343) += bcmdhd_100_10/dhd_custom_memprealloc.o
+obj-$(CONFIG_BCM4343) += bcmdhd_100_10/dhd_custom_exynos.o
+endif
+
+ifneq ($(CONFIG_BCM43454),)
+obj-$(CONFIG_BCM43454)   += bcmdhd_100_10/
+obj-$(CONFIG_BCM43454) += bcmdhd_100_10/dhd_custom_memprealloc.o
+obj-$(CONFIG_BCM43454) += bcmdhd_100_10/dhd_custom_exynos.o
+endif
+
+ifneq ($(CONFIG_BCM43455),)
+obj-$(CONFIG_BCM43455)   += bcmdhd_100_10/
+obj-$(CONFIG_BCM43455) += bcmdhd_100_10/dhd_custom_memprealloc.o
+obj-$(CONFIG_BCM43455) += bcmdhd_100_10/dhd_custom_exynos.o
+endif
+
+ifneq ($(CONFIG_BCM43456),)
+obj-$(CONFIG_BCM43456)   += bcmdhd_100_10/
+obj-$(CONFIG_BCM43456) += bcmdhd_100_10/dhd_custom_memprealloc.o
+obj-$(CONFIG_BCM43456) += bcmdhd_100_10/dhd_custom_exynos.o
+endif
 obj-$(CONFIG_BRCMFMAC)	+= brcm80211/
 obj-$(CONFIG_BRCMSMAC)	+= brcm80211/
-
+obj-$(CONFIG_CNSS_SDIO)	+= cnss/cnss_sdio.o
+obj-$(CONFIG_WCNSS_MEM_PRE_ALLOC) += cnss_prealloc.o
+obj-$(CONFIG_QCA_CLD_WLAN)  += qcacld-2.0/
 obj-$(CONFIG_CW1200)	+= cw1200/
 obj-$(CONFIG_RSI_91X)	+= rsi/
