diff --git a/drivers/media/mtv/mtv23x/Makefile b/drivers/media/mtv/mtv23x/Makefile
new file mode 100755
index 000000000000..b80326d2f089
--- /dev/null
+++ b/drivers/media/mtv/mtv23x/Makefile
@@ -0,0 +1,11 @@
+##########################################
+# Makefile for MTV230 Device Drivers.
+##########################################
+ccflags-y += -Idrivers/media/mtv
+ccflags-y += -Idrivers/media/mtv/mtv23x
+
+obj-y += mtv23x.o
+obj-y += mtv23x_demod.o
+obj-y += mtv23x_rf.o
+obj-y += mtv23x_port.o
+
