diff --git a/drivers/marvell/sd8977/Makefile b/drivers/marvell/sd8977/Makefile
new file mode 100755
index 000000000000..bbdb04861677
--- /dev/null
+++ b/drivers/marvell/sd8977/Makefile
@@ -0,0 +1,7 @@
+#
+# Makefile for sd8977
+#
+#subdir-ccflags-y += -fno-pic
+
+obj-$(CONFIG_MRVL_SDIO_OOB_IRQ)			+= mrvl_sdio.o
+obj-$(CONFIG_MRVL_WL_BUILD_TYPE)		+= mbtc_src/
