diff --git a/fs/ecryptfs/Makefile b/fs/ecryptfs/Makefile
index 49678a69947d..1030a530ddc6 100644
--- a/fs/ecryptfs/Makefile
+++ b/fs/ecryptfs/Makefile
@@ -2,7 +2,10 @@
 # Makefile for the Linux eCryptfs
 #
 
+ccflags-y += -Ifs/sdcardfs/m
+
 obj-$(CONFIG_ECRYPT_FS) += ecryptfs.o
+obj-$(CONFIG_SDP) += ecryptfs_dek.o mm.o ecryptfs_sdp_chamber.o
 
 ecryptfs-y := dentry.o file.o inode.o main.o super.o mmap.o read_write.o \
 	      crypto.o keystore.o kthread.o debug.o
