diff --git a/drivers/media/platform/exynos/fimc-is2/sensor/flite/Makefile b/drivers/media/platform/exynos/fimc-is2/sensor/flite/Makefile
new file mode 100644
index 000000000000..5231d52b07a0
--- /dev/null
+++ b/drivers/media/platform/exynos/fimc-is2/sensor/flite/Makefile
@@ -0,0 +1,7 @@
+obj-$(CONFIG_FIMC_BNS_V2_0) += fimc-is-hw-flite-v2_0.o
+obj-$(CONFIG_FIMC_BNS_V4_0) += fimc-is-hw-flite-v4_0.o
+obj-$(CONFIG_FIMC_BNS_V4_10_0) += fimc-is-hw-flite-v4_10_0.o
+obj-$(CONFIG_FIMC_BNS_V4_20_0) += fimc-is-hw-flite-v4_20_0.o
+
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
