diff --git a/drivers/hid/Makefile b/drivers/hid/Makefile
index b102774b4e16..d069e3e9c647 100644
--- a/drivers/hid/Makefile
+++ b/drivers/hid/Makefile
@@ -118,6 +118,7 @@ obj-$(CONFIG_HID_UCLOGIC)	+= hid-uclogic.o
 obj-$(CONFIG_HID_XINMO)		+= hid-xinmo.o
 obj-$(CONFIG_HID_ZEROPLUS)	+= hid-zpff.o
 obj-$(CONFIG_HID_ZYDACRON)	+= hid-zydacron.o
+obj-$(CONFIG_HID_SYNAPTICS_BT)  += hid-synaptics-bt.o
 
 wacom-objs			:= wacom_wac.o wacom_sys.o
 obj-$(CONFIG_HID_WACOM)		+= wacom.o
