diff --git a/drivers/usb/manager/Makefile b/drivers/usb/manager/Makefile
new file mode 100755
index 000000000000..fcc6409d5869
--- /dev/null
+++ b/drivers/usb/manager/Makefile
@@ -0,0 +1,6 @@
+#
+# Makefile for usb typec manager drivers
+#
+
+obj-$(CONFIG_USB_TYPEC_MANAGER_NOTIFIER)     += usb_typec_manager_notifier.o
+#obj-$(CONFIG_USB_TYPEC_MANAGER)     += usb_typec_manager.o
