diff --git a/drivers/input/touchscreen/synaptics_dsx2/Makefile b/drivers/input/touchscreen/synaptics_dsx2/Makefile
new file mode 100644
index 000000000000..7c0cfa63cf02
--- /dev/null
+++ b/drivers/input/touchscreen/synaptics_dsx2/Makefile
@@ -0,0 +1 @@
+obj-$(CONFIG_TOUCHSCREEN_SYNAPTICS_I2C_DSX2)	+= synaptics_i2c_rmi.o rmi_dev.o rmi_fw_update.o rmi_f54.o
