diff --git a/drivers/gpu/arm/t83x/r15p0/platform/vexpress_6xvirtex7_10mhz/Kbuild b/drivers/gpu/arm/t83x/r15p0/platform/vexpress_6xvirtex7_10mhz/Kbuild
new file mode 100644
index 000000000000..0cb41ce8952d
--- /dev/null
+++ b/drivers/gpu/arm/t83x/r15p0/platform/vexpress_6xvirtex7_10mhz/Kbuild
@@ -0,0 +1,18 @@
+#
+# (C) COPYRIGHT 2012 ARM Limited. All rights reserved.
+#
+# This program is free software and is provided to you under the terms of the
+# GNU General Public License version 2 as published by the Free Software
+# Foundation, and any use by you of this program is subject to the terms
+# of such GNU licence.
+#
+# A copy of the licence is included with the program, and can also be obtained
+# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
+# Boston, MA  02110-1301, USA.
+#
+#
+
+
+
+obj-y += mali_kbase_config_vexpress.o
+obj-y += mali_kbase_cpu_vexpress.o
