diff --git a/drivers/media/mtv/fc8300/Makefile b/drivers/media/mtv/fc8300/Makefile
new file mode 100755
index 000000000000..44d6c8e19c9b
--- /dev/null
+++ b/drivers/media/mtv/fc8300/Makefile
@@ -0,0 +1,17 @@
+obj-y += bbm.o
+obj-y +=fc8300.o
+obj-y +=fc8300_bb.o
+obj-y +=fc8300_cs_tun.o
+obj-y +=fc8300_es1_tun.o
+obj-y +=fc8300_es2_tun.o
+obj-y +=fc8300_i2c.o
+obj-y +=fc8300_isr.o
+obj-y +=fc8300_ppi.o
+obj-y +=fc8300_spi.o
+obj-y +=fc8300_tun.o
+obj-y +=fc8300_tun_table.o
+obj-y +=fci_hal.o
+obj-y +=fci_hpi.o
+obj-y +=fci_oal.o
+obj-y +=fci_ringbuffer.o
+obj-y +=fci_tun.o
