diff --git a/drivers/dma/Makefile b/drivers/dma/Makefile
index cb626c179911..74ca55daaa05 100644
--- a/drivers/dma/Makefile
+++ b/drivers/dma/Makefile
@@ -30,7 +30,7 @@ obj-$(CONFIG_TI_EDMA) += edma.o
 obj-$(CONFIG_STE_DMA40) += ste_dma40.o ste_dma40_ll.o
 obj-$(CONFIG_TEGRA20_APB_DMA) += tegra20-apb-dma.o
 obj-$(CONFIG_S3C24XX_DMAC) += s3c24xx-dma.o
-obj-$(CONFIG_PL330_DMA) += pl330.o
+obj-$(CONFIG_PL330_DMA) += pl330.o samsung-dma.o
 obj-$(CONFIG_PCH_DMA) += pch_dma.o
 obj-$(CONFIG_AMBA_PL08X) += amba-pl08x.o
 obj-$(CONFIG_EP93XX_DMA) += ep93xx_dma.o
