diff --git a/drivers/soc/samsung/pm_domains/Makefile b/drivers/soc/samsung/pm_domains/Makefile
new file mode 100644
index 000000000000..aa9613216596
--- /dev/null
+++ b/drivers/soc/samsung/pm_domains/Makefile
@@ -0,0 +1,6 @@
+#
+# Exynos SoC Specific drivers
+#
+
+obj-$(CONFIG_PM_RUNTIME)        += pm_domains-cal.o
+obj-$(CONFIG_PM_RUNTIME)        += pm_domains_sysfs.o
