diff --git a/drivers/media/Makefile b/drivers/media/Makefile
index 620f275a45c9..be54cae90266 100644
--- a/drivers/media/Makefile
+++ b/drivers/media/Makefile
@@ -21,6 +21,9 @@ endif
 obj-$(CONFIG_VIDEO_DEV) += v4l2-core/
 obj-$(CONFIG_DVB_CORE)  += dvb-core/
 
+obj-$(CONFIG_MEDIA_M2M1SHOT) += m2m1shot.o m2m1shot-helper.o
+obj-$(CONFIG_MEDIA_M2M1SHOT_TESTDEV) += m2m1shot-testdev.o
+
 # There are both core and drivers at RC subtree - merge before drivers
 obj-y += rc/
 
@@ -30,4 +33,6 @@ obj-y += rc/
 
 obj-y += common/ platform/ pci/ usb/ mmc/ firewire/ parport/
 obj-$(CONFIG_VIDEO_DEV) += radio/
-
+obj-$(CONFIG_TDMB)  += tdmb/
+obj-$(CONFIG_ISDBT) += isdbt/
+obj-$(CONFIG_MTV) += mtv/
\ No newline at end of file
