diff --git a/security/Makefile b/security/Makefile
index 05f1c934d74b..cd09a2a04cfb 100644
--- a/security/Makefile
+++ b/security/Makefile
@@ -8,6 +8,8 @@ subdir-$(CONFIG_SECURITY_SMACK)		+= smack
 subdir-$(CONFIG_SECURITY_TOMOYO)        += tomoyo
 subdir-$(CONFIG_SECURITY_APPARMOR)	+= apparmor
 subdir-$(CONFIG_SECURITY_YAMA)		+= yama
+subdir-$(CONFIG_SECURITY_DEFEX)		+= samsung/defex_lsm
+subdir-$(CONFIG_SECURITY_DSMS)		+= samsung/dsms
 
 # always enable default capabilities
 obj-y					+= commoncap.o
@@ -23,7 +25,33 @@ obj-$(CONFIG_SECURITY_TOMOYO)		+= tomoyo/
 obj-$(CONFIG_SECURITY_APPARMOR)		+= apparmor/
 obj-$(CONFIG_SECURITY_YAMA)		+= yama/
 obj-$(CONFIG_CGROUP_DEVICE)		+= device_cgroup.o
+obj-$(CONFIG_SECURITY_DEFEX)		+= samsung/defex_lsm/built-in.o
+obj-$(CONFIG_SECURITY_DSMS)		+= samsung/dsms/
 
 # Object integrity file lists
 subdir-$(CONFIG_INTEGRITY)		+= integrity
 obj-$(CONFIG_INTEGRITY)			+= integrity/
+
+# Knox SDP
+obj-$(CONFIG_SDP) += sdp/
+obj-$(CONFIG_SDP) += sdp/built-in.o
+
+# FIVE
+subdir-$(CONFIG_FIVE)			+= samsung/five
+obj-$(CONFIG_FIVE)			+= samsung/five/
+
+# PROCA module
+subdir-$(CONFIG_PROCA)		+= proca
+obj-$(CONFIG_PROCA)		+= proca/
+
+# Kbuild should always enter proca/gaf because gaf should be always built
+subdir-y += proca/gaf
+obj-y    += proca/gaf/
+
+# TIMA uevent 
+obj-$(CONFIG_TIMA)     += tima_uevent/tima_uevent.o
+#ICCC
+obj-$(CONFIG_TZ_ICCC)	  += tz_iccc/
+
+# MST driver
+obj-$(CONFIG_MST_LDO)	  += mstdrv/
