diff --git a/drivers/power/Makefile b/drivers/power/Makefile
index dfa894273926..fc90e4e038d0 100644
--- a/drivers/power/Makefile
+++ b/drivers/power/Makefile
@@ -55,7 +55,13 @@ obj-$(CONFIG_CHARGER_MAX8998)	+= max8998_charger.o
 obj-$(CONFIG_CHARGER_BQ2415X)	+= bq2415x_charger.o
 obj-$(CONFIG_CHARGER_BQ24190)	+= bq24190_charger.o
 obj-$(CONFIG_CHARGER_BQ24735)	+= bq24735-charger.o
+obj-$(CONFIG_SEC_CHARGER_S2MU003)   += s2mu003_charger.o
+obj-$(CONFIG_SEC_FUELGAUGE_S2MU003)   += s2mu003_fuelgauge.o
+obj-$(CONFIG_SEC_CHARGER_S2MU005)   += s2mu005_charger.o
+obj-$(CONFIG_SEC_FUELGAUGE_S2MU005)   += s2mu005_fuelgauge.o
+obj-$(CONFIG_FUELGAUGE_MAX17058_POWER) += max17058_fuelgauge.o sec_fuelgauge.o
 obj-$(CONFIG_POWER_AVS)		+= avs/
 obj-$(CONFIG_CHARGER_SMB347)	+= smb347-charger.o
 obj-$(CONFIG_CHARGER_TPS65090)	+= tps65090-charger.o
 obj-$(CONFIG_POWER_RESET)	+= reset/
+obj-$(CONFIG_BATTERY_ANDROID)	+= android_battery.o
