diff --git a/drivers/sensorhub/stm_v2/factory/Makefile b/drivers/sensorhub/stm_v2/factory/Makefile
new file mode 100755
index 000000000000..00d2eca28035
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/factory/Makefile
@@ -0,0 +1,14 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+
+obj-$(CONFIG_SENSORS_SSP_ACCELOMETER)		+= Accelometer/ accelometer_sensor.o
+obj-$(CONFIG_SENSORS_SSP_GYROSCOPE)		+= Gyroscope/ gyroscope_sensor.o
+obj-$(CONFIG_SENSORS_SSP_MAGNETIC)	+= Magnetic/ magnetic_sensor.o
+obj-$(CONFIG_SENSORS_SSP_PROXIMITY)	+= Proximity/ proximity_sensor.o
+obj-$(CONFIG_SENSORS_SSP_LIGHT)	+= Light/ light_sensor.o
+obj-$(CONFIG_SENSORS_SSP_BAROMETER) += Barometer/ barometer_sensor.o
+obj-$(CONFIG_SENSORS_SSP_ATUC128L5HAR)	+= mcu_atuc128l5har.o
+obj-$(CONFIG_SENSORS_SSP_MOBEAM)	+= barcode_emulator.o
