diff --git a/drivers/iio/magnetometer/yas537/Makefile b/drivers/iio/magnetometer/yas537/Makefile
new file mode 100755
index 000000000000..df2f84371a04
--- /dev/null
+++ b/drivers/iio/magnetometer/yas537/Makefile
@@ -0,0 +1,5 @@
+#
+# Makefile for industrial I/O Magnetometer sensor drivers
+#
+
+obj-$(CONFIG_SENSORS_YAS_INPUT_MAGNETOMETER)	+= yas_mag_drv-yas537.o yas_mag_kernel.o
