diff --git a/fs/ext4/Makefile b/fs/ext4/Makefile
index 75285ea9aa05..3694537f6282 100644
--- a/fs/ext4/Makefile
+++ b/fs/ext4/Makefile
@@ -2,6 +2,10 @@
 # Makefile for the linux ext4-filesystem routines.
 #
 
+ifeq ($(SEC_BUILD_CONF_QUICK_DMVERITY),true)
+EXTRA_CFLAGS += -DVERIFY_META_ONLY=true
+endif
+
 obj-$(CONFIG_EXT4_FS) += ext4.o
 
 ext4-y	:= balloc.o bitmap.o dir.o file.o fsync.o ialloc.o inode.o page-io.o \
