diff --git a/drivers/usb/Makefile b/drivers/usb/Makefile
index d7be71778059..9ad1d967e772 100644
--- a/drivers/usb/Makefile
+++ b/drivers/usb/Makefile
@@ -62,3 +62,8 @@ obj-$(CONFIG_USB_GADGET)	+= gadget/
 obj-$(CONFIG_USB_COMMON)	+= common/
 
 obj-$(CONFIG_USBIP_CORE)	+= usbip/
+obj-$(CONFIG_USB_NOTIFY_LAYER)	+= notify/
+obj-$(CONFIG_TYPEC)		+= typec/
+ifndef CONFIG_IFPMIC_SUPPORT
+obj-$(CONFIG_USB_TYPEC_MANAGER_NOTIFIER)	+= manager/
+endif
