diff --git a/sound/soc/samsung/seiren/Makefile b/sound/soc/samsung/seiren/Makefile
new file mode 100644
index 000000000000..f45a35f19dc8
--- /dev/null
+++ b/sound/soc/samsung/seiren/Makefile
@@ -0,0 +1,3 @@
+# SEIREN Audio Solution Support
+obj-$(CONFIG_SND_SAMSUNG_SEIREN) += seiren.o
+obj-$(CONFIG_SND_SAMSUNG_ELPE) += lpeffwork.o
