diff --git a/drivers/media/tdmb/mtv319/Makefile b/drivers/media/tdmb/mtv319/Makefile
new file mode 100755
index 000000000000..21d202ae71a3
--- /dev/null
+++ b/drivers/media/tdmb/mtv319/Makefile
@@ -0,0 +1,8 @@
+obj-y  += mtv319.o
+obj-y  += mtv319_port.o
+obj-y  += mtv319_rf.o
+obj-y  += mtv319_ficdec.o
+obj-y  += mtv319_tdmb.o
+obj-y  += mtv319_cifdec.o
+
+ccflags-y += -Idrivers/media/tdmb
