diff --git a/drivers/media/platform/exynos/fimc-is2/sensor/csi2/Makefile b/drivers/media/platform/exynos/fimc-is2/sensor/csi2/Makefile
new file mode 100644
index 000000000000..32a50f42205e
--- /dev/null
+++ b/drivers/media/platform/exynos/fimc-is2/sensor/csi2/Makefile
@@ -0,0 +1,5 @@
+obj-$(CONFIG_CSIS_V4_0) += fimc-is-hw-csi-v4_0.o
+obj-$(CONFIG_CSIS_V4_1) += fimc-is-hw-csi-v4_0.o
+
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
