diff --git a/drivers/sensorhub/stm_v2/factory/Light/Makefile b/drivers/sensorhub/stm_v2/factory/Light/Makefile
new file mode 100755
index 000000000000..3e6d07a6388b
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/factory/Light/Makefile
@@ -0,0 +1,8 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+obj-$(CONFIG_SENSORS_SSP_LIGHT_TMD3725)       += light_tmd3725.o
+obj-$(CONFIG_SENSORS_SSP_LIGHT_TMD3700) += light_tmd3700.o
+obj-$(CONFIG_SENSORS_SSP_LIGHT_TMG399X) += light_tmg399x.o
\ No newline at end of file
