diff --git a/drivers/media/platform/exynos/fimc-is2/sensor/module_framework/flash/Makefile b/drivers/media/platform/exynos/fimc-is2/sensor/module_framework/flash/Makefile
new file mode 100644
index 000000000000..f0b12409f8e0
--- /dev/null
+++ b/drivers/media/platform/exynos/fimc-is2/sensor/module_framework/flash/Makefile
@@ -0,0 +1,10 @@
+obj-$(CONFIG_CAMERA_FLASH_LM3560_OBJ) += fimc-is-device-lm3560.o
+obj-$(CONFIG_CAMERA_FLASH_RT5033_OBJ) += fimc-is-device-rt5033.o
+obj-$(CONFIG_CAMERA_FLASH_GPIO_OBJ) += fimc-is-device-gpio.o
+
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/include
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/vendor
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/hardware/api
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework
+EXTRA_CFLAGS += -Idrivers/media/platform/exynos/fimc-is2/sensor
