diff --git a/include/uapi/linux/Kbuild b/include/uapi/linux/Kbuild
index 8523f9bb72f2..c5363e414073 100644
--- a/include/uapi/linux/Kbuild
+++ b/include/uapi/linux/Kbuild
@@ -112,6 +112,7 @@ header-y += errno.h
 header-y += errqueue.h
 header-y += ethtool.h
 header-y += eventpoll.h
+header-y += exynos_mfc_media.h
 header-y += fadvise.h
 header-y += falloc.h
 header-y += fanotify.h
@@ -189,6 +190,7 @@ header-y += inet_diag.h
 header-y += inotify.h
 header-y += input.h
 header-y += ioctl.h
+header-y += ion.h
 header-y += ip.h
 header-y += ip6_tunnel.h
 header-y += ip_vs.h
@@ -237,6 +239,7 @@ header-y += limits.h
 header-y += llc.h
 header-y += loop.h
 header-y += lp.h
+header-y += m2m1shot.h
 header-y += magic.h
 header-y += major.h
 header-y += map_to_7segment.h
@@ -417,6 +420,8 @@ header-y += veth.h
 header-y += vfio.h
 header-y += vhost.h
 header-y += videodev2.h
+header-y += videodev2_exynos_camera.h
+header-y += videodev2_exynos_media.h
 header-y += virtio_9p.h
 header-y += virtio_balloon.h
 header-y += virtio_blk.h
