diff --git a/drivers/gps/Makefile b/drivers/gps/Makefile
new file mode 100755
index 000000000000..6e4afb8a93db
--- /dev/null
+++ b/drivers/gps/Makefile
@@ -0,0 +1,10 @@
+#
+# Makefile for gps devices
+#
+
+obj-$(CONFIG_GPS_BCMxxxxx)		+= sec_gps_bcm4752.o
+obj-$(CONFIG_GPS_BCM4752)		+= sec_gps_bcm4752.o
+obj-$(CONFIG_GPS_BCM47521)		+= sec_gps_bcm47521.o
+obj-$(CONFIG_GPS_BCM4753)		+= sec_gps_bcm4753.o
+obj-$(CONFIG_GPS_BCM47531)		+= sec_gps_bcm47531.o
+obj-$(CONFIG_GPS_LSI_S5N6420)		+= sec_gps_s5n6420.o
