diff --git a/drivers/staging/sti/abc/Makefile b/drivers/staging/sti/abc/Makefile
new file mode 100644
index 000000000000..f65136a32317
--- /dev/null
+++ b/drivers/staging/sti/abc/Makefile
@@ -0,0 +1,11 @@
+# Samsung sec ABC Feature
+obj-$(CONFIG_SEC_ABC)		+= abc_common.o
+
+# Samsung sec ABC_HUB Feature
+obj-$(CONFIG_SEC_ABC_HUB)	+= abc_hub.o
+
+# Samsung sec ABC_HUB Sub Module(Connect detect) Feature
+obj-$(CONFIG_SEC_ABC_HUB_COND)	+= abc_hub_cond.o
+
+# Samsung sec ABC_HUB Sub Module(Booting time check) Feature
+obj-$(CONFIG_SEC_ABC_HUB_BOOTC)	+= abc_hub_bootc.o
