diff --git a/drivers/ifpmic/muic/Makefile b/drivers/ifpmic/muic/Makefile
new file mode 100644
index 000000000000..d5d858af22af
--- /dev/null
+++ b/drivers/ifpmic/muic/Makefile
@@ -0,0 +1,9 @@
+#
+# Makefile for muic devices
+#
+
+obj-y						+= muic_core.o
+obj-$(CONFIG_MUIC_NOTIFIER)		+= muic_notifier.o
+obj-$(CONFIG_MUIC_S2MU004)		+= s2mu004-muic.o s2mu004-muic-sysfs.o
+obj-$(CONFIG_MUIC_MANAGER)		+= muic_manager.o
+obj-$(CONFIG_HV_MUIC_S2MU004_AFC)	+= s2mu004-muic-afc.o
