diff --git a/mm/Makefile b/mm/Makefile
index da1535fc5d12..0ac65d5ffdb6 100644
--- a/mm/Makefile
+++ b/mm/Makefile
@@ -24,7 +24,7 @@ obj-y			:= filemap.o mempool.o oom_kill.o \
 			   mm_init.o mmu_context.o percpu.o slab_common.o \
 			   compaction.o vmacache.o \
 			   interval_tree.o list_lru.o workingset.o \
-			   iov_iter.o debug.o $(mmu-y)
+			   iov_iter.o debug.o $(mmu-y) showmem_extra.o
 
 obj-y += init-mm.o
 
@@ -76,3 +76,4 @@ obj-$(CONFIG_GENERIC_EARLY_IOREMAP) += early_ioremap.o
 obj-$(CONFIG_CMA)	+= cma.o
 obj-$(CONFIG_MEMORY_BALLOON) += balloon_compaction.o
 obj-$(CONFIG_HARDENED_USERCOPY) += usercopy.o
+obj-$(CONFIG_SEC_PHCOMP)+= phcomp.o
