diff --git a/drivers/sensorhub/stm_v2/factory/Gyroscope/Makefile b/drivers/sensorhub/stm_v2/factory/Gyroscope/Makefile
new file mode 100755
index 000000000000..32aea5e22dbf
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/factory/Gyroscope/Makefile
@@ -0,0 +1,10 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+
+obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_LSM6DSL)	+= gyro_lsm6dsl.o
+obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_K6DS3TR)	+= gyro_k6ds3tr.o
+obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_MPU6500)	+= gyro_mpu6500.o
+obj-$(CONFIG_SENSORS_SSP_GYROSCOPE_BMI168)	+= gyro_bmi168.o
\ No newline at end of file
