diff --git a/drivers/sensorhub/Makefile b/drivers/sensorhub/Makefile
new file mode 100755
index 000000000000..5d32b85f4eaf
--- /dev/null
+++ b/drivers/sensorhub/Makefile
@@ -0,0 +1,6 @@
+#
+# Makefile for the sensor hub.
+#
+
+obj-$(CONFIG_SENSORS_SSP_STM32)	+= stm32/
+obj-$(CONFIG_SENSORS_SSP_STM_V2)		+= stm_v2/
