diff --git a/drivers/gud/gud-exynos7870/Makefile b/drivers/gud/gud-exynos7870/Makefile
new file mode 100644
index 000000000000..de47a669d66c
--- /dev/null
+++ b/drivers/gud/gud-exynos7870/Makefile
@@ -0,0 +1,9 @@
+#
+# Makefile for the <t-base core and trusted UI drivers
+#
+
+obj-$(CONFIG_TRUSTONIC_TEE) := MobiCoreDriver/
+obj-$(CONFIG_TRUSTONIC_TRUSTED_UI) += TlcTui/
+
+obj-$(CONFIG_SECURE_OS_CONTROL) += sec-os-ctrl/
+obj-$(CONFIG_SECURE_OS_BOOSTER_API) += sec-os-booster/
