diff --git a/security/dsms/Makefile b/security/dsms/Makefile
new file mode 100644
index 000000000000..11df6aec7772
--- /dev/null
+++ b/security/dsms/Makefile
@@ -0,0 +1,22 @@
+#
+# Makefile for the DSMS
+#
+
+obj-y := dsms_kernel_api.o
+obj-y += dsms_access_control.o
+obj-y += dsms_policy.o
+obj-y += dsms_init.o
+
+EXTRA_CFLAGS += -DDSMS_WHITELIST_IGNORE_NAME_SUFFIXES_ENABLE
+
+ifneq (,$(filter userdebug eng, $(TARGET_BUILD_VARIANT)))
+
+	EXTRA_CFLAGS += -DDSMS_DEBUG_ENABLE
+	obj-y += dsms_debug.o
+
+	EXTRA_CFLAGS += -DDSMS_DEBUG_TRACE_DSMS_CALLS
+	# EXTRA_CFLAGS += -DDSMS_DEBUG_WHITELIST
+
+	EXTRA_CFLAGS += -DDSMS_KERNEL_ENG
+
+endif
