diff --git a/drivers/media/platform/exynos/Makefile b/drivers/media/platform/exynos/Makefile
new file mode 100644
index 000000000000..3ca997a52530
--- /dev/null
+++ b/drivers/media/platform/exynos/Makefile
@@ -0,0 +1,8 @@
+obj-$(CONFIG_EXYNOS_MEDIA_DEVICE)	+= mdev/
+obj-$(CONFIG_VIDEO_EXYNOS_SCALER)	+= scaler/
+obj-$(CONFIG_VIDEO_EXYNOS_MFC)		+= mfc/
+obj-$(CONFIG_VIDEO_EXYNOS_HEVC)		+= hevc/
+obj-$(CONFIG_VIDEO_EXYNOS_FIMG2D_V5)	+= fimg2d_v5/
+obj-$(CONFIG_VIDEO_EXYNOS_SMFC)		+= smfc/
+obj-$(CONFIG_VIDEO_EXYNOS_FIMC_IS2)	+= fimc-is2/
+EXTRA_CLAGS += -Idrivers/media/video
