diff --git a/drivers/video/fbdev/exynos/decon_7870/Makefile b/drivers/video/fbdev/exynos/decon_7870/Makefile
new file mode 100644
index 000000000000..b908273fa5f8
--- /dev/null
+++ b/drivers/video/fbdev/exynos/decon_7870/Makefile
@@ -0,0 +1,12 @@
+#
+# Copyright (c) 2013 Samsung Electronics Co., Ltd.
+#		http://www.samsung.com
+#
+# Licensed under GPLv2
+#
+
+obj-$(CONFIG_EXYNOS_MIPI_DSI) += dsim.o
+dsim-y += dsim_drv.o dsim_reg_7870.o
+obj-$(CONFIG_EXYNOS_DECON_7870) += decon.o
+decon-y += decon_core.o decon-int_drv.o decon_helper.o decon_reg_7870.o decon_board.o decon_notify.o decon_abd.o
+obj-y += panels/
