diff --git a/drivers/input/touchscreen/sec_incell_ts/Makefile b/drivers/input/touchscreen/sec_incell_ts/Makefile
new file mode 100755
index 000000000000..b3c6aabdf180
--- /dev/null
+++ b/drivers/input/touchscreen/sec_incell_ts/Makefile
@@ -0,0 +1,5 @@
+ifeq ($(CONFIG_SAMSUNG_PRODUCT_SHIP), y)
+  obj-$(CONFIG_TOUCHSCREEN_SEC_INCELL_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o
+else
+  obj-$(CONFIG_TOUCHSCREEN_SEC_INCELL_TS)   += sec_ts.o sec_ts_fw.o sec_ts_fn.o sec_ts_only_vendor.o
+endif
