diff --git a/drivers/gud/gud-exynos7870/sec-os-booster/Makefile b/drivers/gud/gud-exynos7870/sec-os-booster/Makefile
new file mode 100644
index 000000000000..3cef96fb944f
--- /dev/null
+++ b/drivers/gud/gud-exynos7870/sec-os-booster/Makefile
@@ -0,0 +1,12 @@
+#
+# Makefile for Secure OS booster API
+#
+obj-$(CONFIG_SECURE_OS_BOOSTER_API) += sec_os_booster.o
+
+# MobiCore kernel driver path
+GUD_ROOT_FOLDER := drivers/gud/gud-exynos7870
+
+ccflags-y += -Iinclude/soc/samsung/
+# Includes MobiCore kernel driver
+ccflags-y += -I$(GUD_ROOT_FOLDER)/MobiCoreDriver
+ccflags-y += -I$(GUD_ROOT_FOLDER)/MobiCoreDriver/public
