diff --git a/drivers/input/touchscreen/imagis_30xxh/Makefile b/drivers/input/touchscreen/imagis_30xxh/Makefile
new file mode 100644
index 000000000000..803d58bb4358
--- /dev/null
+++ b/drivers/input/touchscreen/imagis_30xxh/Makefile
@@ -0,0 +1,8 @@
+#
+# Makefile for the Imagis touch driver
+#
+
+# Each configuration option enables a list of files.
+
+obj-$(CONFIG_TOUCHSCREEN_IST30XX) += ist30xxh.o ist30xxh_misc.o ist30xxh_sys.o ist30xxh_update.o ist30xxh_sec.o
+obj-$(CONFIG_TOUCHSCREEN_IST3038H) += ist30xxh.o ist30xxh_misc.o ist30xxh_sys.o ist30xxh_update.o ist30xxh_sec.o ist30xxh_cmcs.o
\ No newline at end of file
