diff --git a/drivers/staging/Makefile b/drivers/staging/Makefile
index c780a0e70e15..fea16dd1aa4f 100644
--- a/drivers/staging/Makefile
+++ b/drivers/staging/Makefile
@@ -46,3 +46,6 @@ obj-$(CONFIG_MTD_SPINAND_MT29F)	+= mt29f_spinand/
 obj-$(CONFIG_GS_FPGABOOT)	+= gs_fpgaboot/
 obj-$(CONFIG_CRYPTO_SKEIN)	+= skein/
 obj-$(CONFIG_UNISYSSPAR)	+= unisys/
+obj-$(CONFIG_SEC_EXT)       += samsung/
+obj-$(CONFIG_SEC_STI)		+= sti/
+obj-$(CONFIG_VNSWAP)		+= vnswap/
