diff --git a/drivers/input/wacom/w9019/Makefile b/drivers/input/wacom/w9019/Makefile
new file mode 100755
index 000000000000..3f845fab855b
--- /dev/null
+++ b/drivers/input/wacom/w9019/Makefile
@@ -0,0 +1,2 @@
+
+obj-$(CONFIG_EPEN_WACOM_W9019_GTANOTE)	+= wacom_i2c.o wacom_i2c_firm.o wacom_i2c_func.o w9014_flash.o
