diff --git a/drivers/md/Makefile b/drivers/md/Makefile
index efea0935a4d0..e866c08d9af9 100644
--- a/drivers/md/Makefile
+++ b/drivers/md/Makefile
@@ -1,6 +1,14 @@
 #
 # Makefile for the kernel software RAID and LVM drivers.
 #
+ifeq ($(SEC_BUILD_CONF_QUICK_DMVERITY),true)
+EXTRA_CFLAGS += -DVERIFY_META_ONLY=true
+endif
+
+ifeq ($(SEC_BUILD_CONF_DMV_ALTA),true)
+EXTRA_CFLAGS += -DDMV_ALTA=true
+EXTRA_CFLAGS += -DDMV_ALTA_PROF=true
+endif
 
 dm-mod-y	+= dm.o dm-table.o dm-target.o dm-linear.o dm-stripe.o \
 		   dm-ioctl.o dm-io.o dm-kcopyd.o dm-sysfs.o dm-stats.o
@@ -15,7 +23,7 @@ dm-cache-y	+= dm-cache-target.o dm-cache-metadata.o dm-cache-policy.o
 dm-cache-mq-y   += dm-cache-policy-mq.o
 dm-cache-cleaner-y += dm-cache-policy-cleaner.o
 dm-era-y	+= dm-era-target.o
-dm-verity-y	+= dm-verity-target.o
+dm-verity-y	+= dm-verity-target.o dm-verity-debug.o alta_bigdata.o
 md-mod-y	+= md.o bitmap.o
 raid456-y	+= raid5.o
 
@@ -53,6 +61,7 @@ obj-$(CONFIG_DM_RAID)	+= dm-raid.o
 obj-$(CONFIG_DM_THIN_PROVISIONING)	+= dm-thin-pool.o
 obj-$(CONFIG_DM_VERITY)		+= dm-verity.o
 obj-$(CONFIG_DM_CACHE)		+= dm-cache.o
+obj-$(CONFIG_DM_VERITY)		+= dm-dirty.o
 obj-$(CONFIG_DM_CACHE_MQ)	+= dm-cache-mq.o
 obj-$(CONFIG_DM_CACHE_CLEANER)	+= dm-cache-cleaner.o
 obj-$(CONFIG_DM_ERA)		+= dm-era.o
