diff --git a/drivers/gud/Makefile b/drivers/gud/Makefile
new file mode 100644
index 000000000000..92f35b2416f0
--- /dev/null
+++ b/drivers/gud/Makefile
@@ -0,0 +1,2 @@
+obj-$(CONFIG_SOC_EXYNOS8890) += gud-exynos8890/
+obj-$(CONFIG_SOC_EXYNOS7870) += gud-exynos7870/
