diff --git a/drivers/sensorhub/stm_v2/factory/Proximity/Makefile b/drivers/sensorhub/stm_v2/factory/Proximity/Makefile
new file mode 100755
index 000000000000..0a6ab1290f38
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/factory/Proximity/Makefile
@@ -0,0 +1,10 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+
+obj-$(CONFIG_SENSORS_SSP_PROXIMITY_AUTO_CAL_TMD3725) += prox_autocal_ams.o
+obj-$(CONFIG_SENSORS_SSP_PROXIMITY_TMD3700) += prox_tmd3700.o
+obj-$(CONFIG_SENSORS_SSP_PROXIMITY_TMD3725) += prox_tmd3725.o
+obj-$(CONFIG_SENSORS_SSP_PROXIMITY_TMG399X) += prox_tmg399x.o
\ No newline at end of file
