diff --git a/drivers/gpu/arm/t83x/r7p0/platform/devicetree/Kbuild b/drivers/gpu/arm/t83x/r7p0/platform/devicetree/Kbuild
new file mode 100644
index 000000000000..679945bec523
--- /dev/null
+++ b/drivers/gpu/arm/t83x/r7p0/platform/devicetree/Kbuild
@@ -0,0 +1,16 @@
+#
+# (C) COPYRIGHT 2012-2013 ARM Limited. All rights reserved.
+#
+# This program is free software and is provided to you under the terms of the
+# GNU General Public License version 2 as published by the Free Software
+# Foundation, and any use by you of this program is subject to the terms
+# of such GNU licence.
+#
+# A copy of the licence is included with the program, and can also be obtained
+# from Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
+# Boston, MA  02110-1301, USA.
+#
+#
+
+
+
