diff --git a/crypto/Makefile b/crypto/Makefile
index ea11cf871ebc..6bfff09f8a6f 100644
--- a/crypto/Makefile
+++ b/crypto/Makefile
@@ -2,6 +2,10 @@
 # Cryptographic API
 #
 
+#Keep this on the top
+obj-$(CONFIG_CRYPTO_FIPS) += first_file.o
+obj-$(CONFIG_CRYPTO_FIPS) += fips_integrity.o
+
 obj-$(CONFIG_CRYPTO) += crypto.o
 crypto-y := api.o cipher.o compress.o memneq.o
 
@@ -110,3 +114,6 @@ obj-$(CONFIG_ASYNC_CORE) += async_tx/
 obj-$(CONFIG_ASYMMETRIC_KEY_TYPE) += asymmetric_keys/
 obj-$(CONFIG_CRYPTO_HASH_INFO) += hash_info.o
 obj-$(CONFIG_CRYPTO_ABLK_HELPER) += ablk_helper.o
+
+#Keep this at the bottom
+obj-$(CONFIG_CRYPTO_FIPS) += last_file.o
\ No newline at end of file
