diff --git a/drivers/sensorhub/stm_v2/factory/Barometer/Makefile b/drivers/sensorhub/stm_v2/factory/Barometer/Makefile
new file mode 100755
index 000000000000..2ddca1460549
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/factory/Barometer/Makefile
@@ -0,0 +1,8 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS22H)	+= barometer_lps22h.o
+obj-$(CONFIG_SENSORS_SSP_BAROMETER_LPS25H)	+= barometer_lps25h.o
+obj-$(CONFIG_SENSORS_SSP_BAROMETER_BMP280)	+= barometer_bmp280.o
