diff --git a/drivers/sensorhub/stm_v2/factory/Magnetic/Makefile b/drivers/sensorhub/stm_v2/factory/Magnetic/Makefile
new file mode 100755
index 000000000000..942abaac7518
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/factory/Magnetic/Makefile
@@ -0,0 +1,12 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+
+obj-$(CONFIG_SENSORS_SSP_MAGNETIC_AK09918C) += magnetic_ak09918c.o
+obj-$(CONFIG_SENSORS_SSP_MAGNETIC_AK09916C) += magnetic_ak09916c.o
+obj-$(CONFIG_SENSORS_SSP_MAGNETIC_AK09911) += magnetic_ak09911.o
+obj-$(CONFIG_SENSORS_SSP_MAGNETIC_LSM303AH)	+= magnetic_lsm303ah.o
+obj-$(CONFIG_SENSORS_SSP_MAGNETIC_YAS539)	+= magnetic_yas539.o
+
