diff --git a/drivers/gud/gud-exynos8890/sec-os-ctrl/Makefile b/drivers/gud/gud-exynos8890/sec-os-ctrl/Makefile
new file mode 100644
index 000000000000..2f414b09753a
--- /dev/null
+++ b/drivers/gud/gud-exynos8890/sec-os-ctrl/Makefile
@@ -0,0 +1,11 @@
+#
+# Makefile for Secure OS control sysfs
+#
+obj-$(CONFIG_SECURE_OS_CONTROL) += sec_os_ctrl.o
+
+# MobiCore kernel driver path
+GUD_ROOT_FOLDER := drivers/gud/
+
+# Includes MobiCore kernel driver
+ccflags-y += -I$(GUD_ROOT_FOLDER)/MobiCoreDriver
+ccflags-y += -I$(GUD_ROOT_FOLDER)/MobiCoreDriver/public
