diff --git a/drivers/input/touchscreen/stm/Makefile b/drivers/input/touchscreen/stm/Makefile
new file mode 100644
index 000000000000..8b3f4728c16b
--- /dev/null
+++ b/drivers/input/touchscreen/stm/Makefile
@@ -0,0 +1 @@
+obj-$(CONFIG_TOUCHSCREEN_FTS)	+= fts_ts.o fts_fwu.o
\ No newline at end of file
