diff --git a/drivers/bts/Makefile b/drivers/bts/Makefile
new file mode 100644
index 000000000000..671b7bc40b50
--- /dev/null
+++ b/drivers/bts/Makefile
@@ -0,0 +1,6 @@
+#
+# Makefile for BTS.
+#
+
+obj-$(CONFIG_EXYNOS8890_BTS)    += cal_bts8890.o bts-exynos8890.o
+obj-$(CONFIG_EXYNOS7870_BTS)    += cal_bts7870.o bts-exynos7870.o
