diff --git a/drivers/sensorhub/stm_v2/Makefile b/drivers/sensorhub/stm_v2/Makefile
new file mode 100755
index 000000000000..e6fabfbfda11
--- /dev/null
+++ b/drivers/sensorhub/stm_v2/Makefile
@@ -0,0 +1,9 @@
+#
+# Makefile for the sensor drivers.
+#
+
+# Each configuration option enables a list of files.
+obj-$(CONFIG_SENSORS_SSP)		+= sensors_core.o ssp_dev.o ssp_comm.o ssp_data.o ssp_sysfs.o \
+						ssp_iio.o ssp_firmware.o ssp_debug.o ssp_sensorhub.o \
+						ssp_sensor_dump.o \
+						factory/
\ No newline at end of file
