diff --git a/drivers/input/wacom/Makefile b/drivers/input/wacom/Makefile
new file mode 100644
index 000000000000..2210a650859c
--- /dev/null
+++ b/drivers/input/wacom/Makefile
@@ -0,0 +1,5 @@
+
+obj-$(CONFIG_INPUT_WACOM)	+= wacom_i2c.o wacom_i2c_sec.o
+obj-$(CONFIG_EPEN_WACOM_W9018)	+= w9018_flash.o
+obj-$(CONFIG_EPEN_WACOM_W9019)	+= w9019_flash.o
+obj-$(CONFIG_EPEN_WACOM_W9019_GTANOTE)	+= w9019/
